language: php

php:
  - 7.1
  - 7.2

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --no-interaction --no-suggest

script:
  - composer test
  - composer check-style
